### ISSUE TITLE
Cannot get beyond block 1

### ISSUE THREAD

**Issue by sorcer1122** [ziesha-network/bazuka#49]
Hi, my zeeka node was working fine until an update one day, probably a month or so ago. Now it does not go beyond block one and I can see 'wrong network' error in logs.

I tried various ways to fix it but nothing helps.
Any suggestions please?

**Comment by keyvank** [comment]
You were probably running on a wrong network. Check your `network` property in `~/.bazuka.yaml` file and make sure you are also using healthy bootstrap nodes.
